#!/bin/sh -e

#
# bootstrap - script to bootstrap the distribution rolling engine
#
# to build a tarball, ready for distribution, from fresh checked out
# cvs sources, do
#
#     automake --add-missing && ./bootstrap && ./configure && make distcheck
#
# this will yield a tarball.  Once this has been
# run, one can, after e.g. editing sources, run just
#
#     make distcheck
#
# to generate a new tarball.  (No need to run ./bootstrap again in this case.)
# After downloading, users do
#
#    tar xzf somedist.tar.gz
#    cd somedist
#    ./configure && make
#    make install
#

set -x

if test ! -f VERSION
then
    shed/setversion
fi

aclocal \
    && autoheader \
    && automake --verbose --gnu --add-missing \
    && autoconf



